### PR TITLE
setup: use pipenv and pbr

### PR DESCRIPTION
**Pull request by greut**
the pip-tools alternative.

```console
% pipenv lock -r > requirements.txt
```

### CODE REVIEW

**Review by chrisglass — COMMENTED** [review]
Why is this change needed?

The PR describes what is being done, but not *why*.

**Comment by greut** [comment]
pipenv is awesome and requests has a CVE.

**Comment by brutasse** [comment]
> requests has a CVE

The PR description & diff doesn't make that very clear. A separate PR could be merged right away.

pip-tools is de facto what we're using on all python projects. A standard way of doing things within a team has its advantages, so if we need to change tools it's worth discussing what evolutions we want and apply them everywhere.

**Comment by greut** [comment]
the manual splitlines on the reqs.txt is quite a hack as well.

**Comment by pyr** [comment]
> A standard way of doing things within a team has its advantages, so if we need to change tools it's worth discussing what evolutions we want and apply them everywhere.

This is the salient point here. Moreover, it is the responsibility of the proposer to try and recognize when divergence is introduced with a clear motivation for said divergence.

**Comment by greut** [comment]
fair enough.

**Pull request closed without merging**
